#!/bin/bash
# start-all.sh
#
# Starts all 4 Spring Boot services in the background using their built jars.
# Assumes:
#   - Kafka (KRaft mode) is already running on localhost:9092 (start it yourself, see README)
#   - Redis is already running on localhost:6379 (WSL: `redis-server --daemonize yes`)
#   - You've already run `mvn clean package` in each of the 4 project folders
#
# Run this from the project root: ./scripts/start-all.sh

set -e

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$ROOT_DIR/logs"
# WSL_IP="$(hostname -I | awk '{print $1}')"
mkdir -p "$LOG_DIR"

# RUNTIME_CONFIG_FILE="$ROOT_DIR/dashboard/runtime-config.js"
# cat > "$RUNTIME_CONFIG_FILE" <<EOF
# // Generated by scripts/start-all.sh
# window.CONFIG_TOWER_RUNTIME = {
#   backendHost: "http://${WSL_IP}"
# };
# EOF

start_service() {
  local name=$1
  local dir=$2
  local jar
  jar=$(find "$dir/target" -maxdepth 1 -name "*.jar" ! -name "*.original" | head -n 1)

  if [ -z "$jar" ]; then
    echo "  [SKIP] No jar found for $name in $dir/target - did you run 'mvn clean package'?"
    return
  fi

  echo "  Starting $name from $jar ..."
  nohup java -jar "$jar" > "$LOG_DIR/$name.log" 2>&1 &
  echo $! > "$LOG_DIR/$name.pid"
}

wait_for_http() {
  local name=$1
  local url=$2
  local timeout_seconds=${3:-60}
  local elapsed=0

  echo -n "  Waiting for $name to become ready"
  while true; do
    if curl -s -o /dev/null -f "$url"; then
      echo ""
      echo "  $name is ready"
      return 0
    fi

    if [ "$elapsed" -ge "$timeout_seconds" ]; then
      echo ""
      echo "  ERROR: $name did not become ready within ${timeout_seconds}s"
      echo "  Check $LOG_DIR/$name.log"
      return 1
    fi

    echo -n "."
    sleep 1
    elapsed=$((elapsed + 1))
  done
}

echo "Checking Kafka is reachable on localhost:9092 ..."
if ! (echo > /dev/tcp/localhost/9092) 2>/dev/null; then
  echo "  WARNING: Kafka doesn't seem to be listening on 9092. Start it first (see README)."
fi

echo "Checking Redis is reachable on localhost:6379 ..."
if ! redis-cli -h localhost -p 6379 ping > /dev/null 2>&1; then
  echo "  WARNING: Redis doesn't seem to respond to PING. Start it first: redis-server --daemonize yes"
fi

echo "Starting services ..."
start_service "config-server" "$ROOT_DIR/config-server"
wait_for_http "config-server" "http://localhost:8084/api/config/health" 90
start_service "payments" "$ROOT_DIR/microservices/payments"
start_service "auth" "$ROOT_DIR/microservices/auth"
start_service "inventory" "$ROOT_DIR/microservices/inventory"

wait_for_http "payments" "http://localhost:8081/api/payments/health" 90
wait_for_http "auth" "http://localhost:8082/api/auth/health" 90
wait_for_http "inventory" "http://localhost:8083/api/inventory/health" 90

echo ""
echo "All services launching. PIDs and logs are in $LOG_DIR"
echo "  config-server : http://localhost:8084/api/config/health"
echo "  payments      : http://localhost:8081/api/payments/health"
echo "  auth          : http://localhost:8082/api/auth/health"
echo "  inventory     : http://localhost:8083/api/inventory/health"
# echo "  dashboard     : use backend host http://${WSL_IP}"
echo ""
echo "Tail logs with: tail -f $LOG_DIR/<service>.log"
echo "Stop everything with: ./scripts/stop-all.sh"
